# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

#    - name: Build with Maven
#      run: mvn -B package --file pom.xml

    - name: debug GITHUB_ACTOR
      run: echo $GITHUB_ACTOR
      env:
        GITHUB_ACTOR: ${{ github.actor }}

    - name: debug GITHUB_TOKEN
      run: echo $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: debug PACKAGE_ACCESS_TOKEN
      run: echo $PACKAGE_ACCESS_TOKEN
      env:
        PACKAGE_ACCESS_TOKEN: ${{ vars.PACKAGE_ACCESS_TOKEN }}


#    - name: Run open rewrite
      #run: mvn rewrite:run -s .m2/settings.xml
#      env:
#        GITHUB_ACTOR: ${{ github.actor }}
#        GITHUB_TOKEN: ${{ github.token }}

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_ACTOR: ${{ github.actor }}
#        GITHUB_TOKEN: ${{ github.token }}
